spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nest_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 3000

jwt:
  secret: 0a0c28773f3b6529ebe4c140f05354aa86fa5da4771d9ed6768137860244bb42
  expiration: 86400000
  refresh-token-expiration: 604800000