spring:
  application:
    name: java-admin-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/nest_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.admin.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开发时打印 SQL
  global-config:
    db-config:
      logic-delete-field: deleted      # 全局逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
  spring-boot:
    # 启用 Spring Boot 自动配置
    enabled: true

server:
  port: 3000
  servlet:
    context-path: /api

jwt:
  secret: 0a0c28773f3b6529ebe4c140f05354aa86fa5da4771d9ed6768137860244bb42
  expiration: 86400000
  refresh-token-expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.example.admin.controller
  paths-to-match: /**